apiversion: networking.k8s.io/v1
kind: ingress
metadata:
  name: ing-traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathtype: prefix
            backend:
              service:
                name: ws-cpt-go
                port:
                  number: 80