apiVersion: v1
kind: Service
metadata:
  name: ws-cpt-go
spec:
  ports:
    - port: 80
      name: web
      targetPort: web
  type: LoadBalancer
  loadBalancerIP: "35.246.194.219"
  selector:
    app: ws-cpt-go