apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ws-cpt-go
spec:
  selector:
    matchLabels:
      app: ws-cpt-go
  serviceName: "ws-cpt-go"
  replicas: 1
  template:
    metadata:
      labels:
        app: ws-cpt-go
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ws-cpt-go
          image: europe-west3-docker.pkg.dev/valiuz-sbx-cde/registry/ws-cpt-go:1.01
          ports:
            - containerPort: 80
              name: web
#          volumeMounts:
#            - name: www
#              mountPath: /app
#  volumeClaimTemplates:
#    - metadata:
#        name: www
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: standard
#        resources:
#          requests:
#            storage: 1Mi